"""Tests for firewall granularity settings (Phase 2).

Validates the 3 new settings fields are properly registered and that
nftables rule generation patterns work with various input combinations.
"""

import os
from unittest.mock import patch

import pytest


class TestFirewallSettings:
    """Verify firewall fields are registered in CONFIGURABLE_FIELDS."""

    def test_fields_registered(self):
        from api.services.settings import CONFIGURABLE_FIELDS

        assert "firewall_vpn_input_ports" in CONFIGURABLE_FIELDS
        assert "firewall_outbound_subnets" in CONFIGURABLE_FIELDS
        assert "firewall_custom_rules_file" in CONFIGURABLE_FIELDS

    def test_defaults_are_empty(self):
        from api.services.settings import CONFIGURABLE_FIELDS

        assert CONFIGURABLE_FIELDS["firewall_vpn_input_ports"]["default"] == ""
        assert CONFIGURABLE_FIELDS["firewall_outbound_subnets"]["default"] == ""
        assert CONFIGURABLE_FIELDS["firewall_custom_rules_file"]["default"] == ""

    def test_not_secret(self):
        from api.services.settings import CONFIGURABLE_FIELDS

        assert CONFIGURABLE_FIELDS["firewall_vpn_input_ports"]["secret"] is False
        assert CONFIGURABLE_FIELDS["firewall_outbound_subnets"]["secret"] is False
        assert CONFIGURABLE_FIELDS["firewall_custom_rules_file"]["secret"] is False

    def test_config_fields_exist(self):
        from api.config import Config

        config = Config()
        assert config.firewall_vpn_input_ports == ""
        assert config.firewall_outbound_subnets == ""
        assert config.firewall_custom_rules_file == ""

    def test_config_reads_env(self):
        from api.config import Config

        env = {
            "FIREWALL_VPN_INPUT_PORTS": "51413,6881",
            "FIREWALL_OUTBOUND_SUBNETS": "192.168.1.0/24,10.0.0.0/8",
            "FIREWALL_CUSTOM_RULES_FILE": "/config/custom.nft",
        }
        with patch.dict(os.environ, env, clear=False):
            config = Config()
        assert config.firewall_vpn_input_ports == "51413,6881"
        assert config.firewall_outbound_subnets == "192.168.1.0/24,10.0.0.0/8"
        assert config.firewall_custom_rules_file == "/config/custom.nft"

    def test_load_settings_returns_firewall_fields(self, tmp_path):
        from api.services.settings import load_settings

        yaml_file = tmp_path / "nonexistent.yml"
        env = {"FIREWALL_VPN_INPUT_PORTS": "8080"}
        with patch.dict(os.environ, env, clear=False), \
             patch("api.services.settings.SETTINGS_PATH", yaml_file):
            settings = load_settings()
        assert settings["firewall_vpn_input_ports"] == "8080"

    def test_settings_update_model_has_fields(self):
        from api.routes.settings import SettingsUpdate

        model = SettingsUpdate(
            firewall_vpn_input_ports="51413",
            firewall_outbound_subnets="10.0.0.0/8",
            firewall_custom_rules_file="/config/fw.nft",
        )
        assert model.firewall_vpn_input_ports == "51413"


class TestFirewallRulePatterns:
    """Verify nftables rule patterns generated by the killswitch script.

    These test the logic patterns rather than running the actual shell script.
    """

    def test_vpn_input_ports_parsing(self):
        """Comma-separated ports should produce individual accept rules."""
        ports = "51413,6881,8080"
        parsed = [p.strip() for p in ports.split(",") if p.strip()]
        assert parsed == ["51413", "6881", "8080"]
        for port in parsed:
            assert port.isdigit()

    def test_empty_ports_produce_no_rules(self):
        """Empty string should produce no extra rules."""
        ports = ""
        parsed = [p.strip() for p in ports.split(",") if p.strip()]
        assert parsed == []

    def test_outbound_subnets_parsing(self):
        """Comma-separated CIDRs should be parseable."""
        subnets = "192.168.1.0/24, 10.0.0.0/8"
        parsed = [s.strip() for s in subnets.split(",") if s.strip()]
        assert parsed == ["192.168.1.0/24", "10.0.0.0/8"]

    def test_custom_rules_file_only_loaded_when_exists(self, tmp_path):
        """Custom rules file should only be loaded if it exists."""
        rules_file = tmp_path / "custom.nft"
        assert not rules_file.exists()

        # If file doesn't exist, it should be skipped
        rules_file.write_text("# custom rules\n")
        assert rules_file.exists()
        assert rules_file.read_text() == "# custom rules\n"


class TestPreVpnFirewall:
    """Verify init-firewall-pre endpoint parsing logic.

    Tests the pattern logic used by the pre-VPN firewall script to parse
    WireGuard/OpenVPN configs and distinguish IPs from hostnames.
    """

    def _parse_wg_endpoint(self, conf_text):
        """Replicate the WireGuard endpoint parsing from init-firewall-pre.sh."""
        import re

        for line in conf_text.splitlines():
            if re.match(r"^\s*Endpoint\s*=", line, re.IGNORECASE):
                raw = line.split("=", 1)[1].strip().strip("[]")
                # Strip port
                port_match = re.search(r":(\d+)$", raw)
                port = port_match.group(1) if port_match else "51820"
                host = re.sub(r":\d+$", "", raw).strip("[]")
                return host, port
        return None, None

    def _parse_ovpn_remote(self, conf_text):
        """Replicate the OpenVPN remote line parsing from init-firewall-pre.sh."""
        for line in conf_text.splitlines():
            parts = line.strip().split()
            if parts and parts[0].lower() == "remote":
                host = parts[1] if len(parts) > 1 else None
                port = parts[2] if len(parts) > 2 else "1194"
                return host, port
        return None, None

    def _is_ipv4(self, host):
        import re
        return bool(re.match(r"^\d+\.\d+\.\d+\.\d+$", host or ""))

    # --- WireGuard endpoint parsing ---

    def test_wg_ip_endpoint_parsed(self):
        conf = "[Peer]\nEndpoint = 198.51.100.42:51820\n"
        host, port = self._parse_wg_endpoint(conf)
        assert host == "198.51.100.42"
        assert port == "51820"
        assert self._is_ipv4(host)

    def test_wg_hostname_endpoint_detected(self):
        conf = "[Peer]\nEndpoint = nyc-001.example.vpn:51820\n"
        host, port = self._parse_wg_endpoint(conf)
        assert host == "nyc-001.example.vpn"
        assert port == "51820"
        assert not self._is_ipv4(host)

    def test_wg_nonstandard_port(self):
        conf = "[Peer]\nEndpoint = 203.0.113.7:1337\n"
        host, port = self._parse_wg_endpoint(conf)
        assert host == "203.0.113.7"
        assert port == "1337"

    def test_wg_no_endpoint_returns_none(self):
        conf = "[Interface]\nPrivateKey = abc123\n"
        host, port = self._parse_wg_endpoint(conf)
        assert host is None
        assert port is None

    def test_wg_endpoint_case_insensitive(self):
        conf = "[Peer]\nendpoint = 198.51.100.1:51820\n"
        host, port = self._parse_wg_endpoint(conf)
        assert host == "198.51.100.1"

    # --- OpenVPN remote parsing ---

    def test_ovpn_ip_remote_parsed(self):
        conf = "remote 198.51.100.10 1194\nproto udp\n"
        host, port = self._parse_ovpn_remote(conf)
        assert host == "198.51.100.10"
        assert port == "1194"
        assert self._is_ipv4(host)

    def test_ovpn_hostname_remote_detected(self):
        conf = "remote vpn.example.com 443\nproto tcp\n"
        host, port = self._parse_ovpn_remote(conf)
        assert host == "vpn.example.com"
        assert port == "443"
        assert not self._is_ipv4(host)

    def test_ovpn_default_port_when_missing(self):
        conf = "remote 203.0.113.5\n"
        host, port = self._parse_ovpn_remote(conf)
        assert host == "203.0.113.5"
        assert port == "1194"

    def test_ovpn_no_remote_returns_none(self):
        conf = "proto udp\ndev tun\n"
        host, port = self._parse_ovpn_remote(conf)
        assert host is None
        assert port is None

    # --- Setup mode detection ---

    def test_setup_mode_when_no_configs(self, tmp_path):
        """When no WG or OVPN config exists, pre-firewall should skip (setup mode)."""
        wg_dir = tmp_path / "wireguard"
        ovpn_dir = tmp_path / "openvpn"
        wg_dir.mkdir()
        ovpn_dir.mkdir()

        wg_configs = list(wg_dir.glob("*.conf"))
        ovpn_configs = list(ovpn_dir.glob("*.ovpn")) + list(ovpn_dir.glob("*.conf"))

        assert wg_configs == []
        assert ovpn_configs == []
        # No configs → setup mode → pre-firewall skips

    def test_wg_config_triggers_pre_firewall(self, tmp_path):
        """A WireGuard config file causes pre-firewall to engage."""
        wg_dir = tmp_path / "wireguard"
        wg_dir.mkdir()
        conf = wg_dir / "wg0.conf"
        conf.write_text("[Interface]\nPrivateKey = abc\n[Peer]\nEndpoint = 198.51.100.1:51820\n")

        wg_configs = list(wg_dir.glob("*.conf"))
        assert len(wg_configs) == 1
