"""Tests for firewall granularity settings (Phase 2).

Validates the 3 new settings fields are properly registered and that
nftables rule generation patterns work with various input combinations.
"""

import os
from unittest.mock import patch

import pytest


class TestFirewallSettings:
    """Verify firewall fields are registered in CONFIGURABLE_FIELDS."""

    def test_fields_registered(self):
        from api.services.settings import CONFIGURABLE_FIELDS

        assert "firewall_vpn_input_ports" in CONFIGURABLE_FIELDS
        assert "firewall_outbound_subnets" in CONFIGURABLE_FIELDS
        assert "firewall_custom_rules_file" in CONFIGURABLE_FIELDS

    def test_defaults_are_empty(self):
        from api.services.settings import CONFIGURABLE_FIELDS

        assert CONFIGURABLE_FIELDS["firewall_vpn_input_ports"]["default"] == ""
        assert CONFIGURABLE_FIELDS["firewall_outbound_subnets"]["default"] == ""
        assert CONFIGURABLE_FIELDS["firewall_custom_rules_file"]["default"] == ""

    def test_not_secret(self):
        from api.services.settings import CONFIGURABLE_FIELDS

        assert CONFIGURABLE_FIELDS["firewall_vpn_input_ports"]["secret"] is False
        assert CONFIGURABLE_FIELDS["firewall_outbound_subnets"]["secret"] is False
        assert CONFIGURABLE_FIELDS["firewall_custom_rules_file"]["secret"] is False

    def test_config_fields_exist(self):
        from api.config import Config

        config = Config()
        assert config.firewall_vpn_input_ports == ""
        assert config.firewall_outbound_subnets == ""
        assert config.firewall_custom_rules_file == ""

    def test_config_reads_env(self):
        from api.config import Config

        env = {
            "FIREWALL_VPN_INPUT_PORTS": "51413,6881",
            "FIREWALL_OUTBOUND_SUBNETS": "192.168.1.0/24,10.0.0.0/8",
            "FIREWALL_CUSTOM_RULES_FILE": "/config/custom.nft",
        }
        with patch.dict(os.environ, env, clear=False):
            config = Config()
        assert config.firewall_vpn_input_ports == "51413,6881"
        assert config.firewall_outbound_subnets == "192.168.1.0/24,10.0.0.0/8"
        assert config.firewall_custom_rules_file == "/config/custom.nft"

    def test_load_settings_returns_firewall_fields(self, tmp_path):
        from api.services.settings import load_settings

        yaml_file = tmp_path / "nonexistent.yml"
        env = {"FIREWALL_VPN_INPUT_PORTS": "8080"}
        with patch.dict(os.environ, env, clear=False), \
             patch("api.services.settings.SETTINGS_PATH", yaml_file):
            settings = load_settings()
        assert settings["firewall_vpn_input_ports"] == "8080"

    def test_settings_update_model_has_fields(self):
        from api.routes.settings import SettingsUpdate

        model = SettingsUpdate(
            firewall_vpn_input_ports="51413",
            firewall_outbound_subnets="10.0.0.0/8",
            firewall_custom_rules_file="/config/fw.nft",
        )
        assert model.firewall_vpn_input_ports == "51413"


class TestFirewallRulePatterns:
    """Verify nftables rule patterns generated by the killswitch script.

    These test the logic patterns rather than running the actual shell script.
    """

    def test_vpn_input_ports_parsing(self):
        """Comma-separated ports should produce individual accept rules."""
        ports = "51413,6881,8080"
        parsed = [p.strip() for p in ports.split(",") if p.strip()]
        assert parsed == ["51413", "6881", "8080"]
        for port in parsed:
            assert port.isdigit()

    def test_empty_ports_produce_no_rules(self):
        """Empty string should produce no extra rules."""
        ports = ""
        parsed = [p.strip() for p in ports.split(",") if p.strip()]
        assert parsed == []

    def test_outbound_subnets_parsing(self):
        """Comma-separated CIDRs should be parseable."""
        subnets = "192.168.1.0/24, 10.0.0.0/8"
        parsed = [s.strip() for s in subnets.split(",") if s.strip()]
        assert parsed == ["192.168.1.0/24", "10.0.0.0/8"]

    def test_custom_rules_file_only_loaded_when_exists(self, tmp_path):
        """Custom rules file should only be loaded if it exists."""
        rules_file = tmp_path / "custom.nft"
        assert not rules_file.exists()

        # If file doesn't exist, it should be skipped
        rules_file.write_text("# custom rules\n")
        assert rules_file.exists()
        assert rules_file.read_text() == "# custom rules\n"
