[BitTorrent]
Session\BTProtocol=Both
Session\DefaultSavePath=/downloads
Session\TempPath=/downloads/temp
Session\Interface=
Session\InterfaceName=
Session\Port=6881

[Network]
PortForwardingEnabled=false

[Preferences]
WebUI\Port=8080
WebUI\Address=0.0.0.0
WebUI\HostHeaderValidation=false
WebUI\CSRFProtection=false
WebUI\Username=admin
General\Locale=en
Downloads\SavePath=/downloads
